# Generated by Django 4.2.4 on 2023-08-21 14:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('type', models.CharField(choices=[('NONE', 'None'), ('WITHDRAW', 'Withdraw'), ('DEPOSIT', 'Deposit'), ('TRANSFER', 'Transfer')], default=None, max_length=50)),
                ('status', models.CharField(choices=[('NONE', 'None'), ('SUCCESSFUL', 'Successful'), ('PENDING', 'Pending'), ('DECLINED', 'Declined')], default=None, max_length=50)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('amount', models.BigIntegerField()),
                ('pk_reference_number', models.UUIDField(default=uuid.UUID, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('balance', models.DecimalField(decimal_places=2, max_digits=9)),
                ('wallet_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
